steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/trive-api:$COMMIT_SHA', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/trive-api:$COMMIT_SHA']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - 'trive-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/trive-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--memory'
      - '1024Mi'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/trive-api:$COMMIT_SHA'
logsBucket: 'gs://trive-project/logs'
